config/routes.rb
Rails.application.routes.draw do

  root 'stocks#index'

  get '/ping' => 'status#ping'

  resources :stocks do
    member do
      post 'crawl_posts'
      post 'update_weights'
    end

    collection do
      post 'crawl_posts_multiple'
      post 'update_weights_multiple'
    end

    resources :posts do
      collection do
        get 'chart'
      end
    end
  end

  resources :posts do
    collection do
      get 'download_monthly_summary', format: :csv
    end
  end

  resources :words

  resources :baidu_news, only: [:index, :create, :show, :destroy] do
    member do
      get 'download', format: :csv
    end
  end

end

app/models/stock.rb
require 'csv'

class Stock < ActiveRecord::Base
  self.primary_key = :stock_id
  self.per_page = 20

  has_many :posts, :foreign_key => :stock_id

  attr_accessor :max_possible_post_created_dt
  attr_reader :posts_path, :posts_path_no_html

  after_initialize :set_posts_path

  validates :stock_id, presence: true, uniqueness: true, numericality: { only_integer: true }

  scope :has_stock_name, -> { where("stock_name IS NOT NULL") }

  STATUS = {
    :crawling => "CRAWLING",
    :crawled => "CRAWLED",
    :updating => "UPDATING",
    :updated => "UPDATED",
    :update_failure => "UPDT FAIL",
    :time_crawling => "TIME CRAWLING",
    :time_updated => "TIME UPDT"
  }

  BASE = "http://guba.eastmoney.com"
  PER_PAGE = 1000

  def self.crawl_and_update_all
    Rails.logger.info "Crawl and update all stocks #{Time.now}"
    Stock.find_each do |stock|
      stock.crawl_and_update if stock.idle?
    end
  end

  def self.create_by_stock_ids(stock_ids, delete_old_records=false)
    ActiveRecord::Base.connection.execute("TRUNCATE stocks") if delete_old_records
    failed_to_create = []
    CSV.parse(stock_ids) do |row|
      stock_id = row.first.split('.').first
      stock = nil
      stock = Stock.find_by(stock_id: stock_id) unless delete_old_records
      stock = Stock.new(stock_id: stock_id) if stock.blank?
      unless stock.save
        Rails.logger.error "Stock ID #{stock_id}: #{stock.errors.full_messages.join(". ")}"
        failed_to_create << row
      end
    end
    failed_to_create
  end

  def stock_name_gbk
    stock_name_stripped.encode('gb2312', 'utf-8')
  end

  def stock_name_stripped
    self.stock_name[-1] == '吧' ? self.stock_name[0..-2] : self.stock_name if self.stock_name
  end

  def crawl_and_update
    crawl_posts_without_delay
    update_word_analysis_without_delay
  end

  def crawl_posts
    self.status = STATUS[:crawling]
    self.save!

    posts_path = self.posts_path
    Rails.logger.info "Start to crawl: #{BASE}/#{posts_path}"
    
    # Fetch exact post create date for the first page, since there will be recommended topics that not follow chronicle order
    first_page = posts_by_page(BASE, self.posts_path, true)

    page_strings = first_page["page_calculation"].split("|")
    posts_count = page_strings[-3].to_i
    posts_per_page = page_strings[-2].to_f
    pages_count = (posts_count / posts_per_page).ceil
    Rails.logger.info "Number of pages: #{pages_count}"

    #if self.stock_id != first_page["stock_code"]
    #  raise "Stock ID is incorrect: #{stock_id} vs #{first_page["stock_code"]}"
    #end
    self.stock_name = first_page["stock_name"]
    
    continue_to_crawl = save_posts(first_page["posts"], first_page["posts_detail"], (Time.now-1.year))
    current_page = 2
    while(current_page <= pages_count and continue_to_crawl) do
      posts_path_current_page = "#{self.posts_path_no_html}_#{current_page}.html"
      Rails.logger.info "URL: #{posts_path_current_page}"
      data = posts_by_page(BASE, posts_path_current_page, false)
      continue_to_crawl = save_posts(data["posts"])
      current_page += 1
    end

    self.status = STATUS[:crawled]
    self.total_posts = self.posts.size
    self.save!
    return true
  end

  def update_posts_create_time
    self.status = STATUS[:time_crawling]
    self.save!

    Rails.logger.info "Start to update posts create time for Stock: #{self.stock_id}"

    Stock.transaction do
      self.posts.find_each do |post|
        Rails.logger.info "Post create time update for: #{post.id}"
        data = post_by_page(BASE, "/#{post.path}")

        if data["post_created_at"]
          post.post_created_at = parse_post_create_time(data["post_created_at"])
          post.status = Post::STATUS[:post_create_time_updated]
        else
          Rails.logger.error "Failed to fetch Post Create Time for post: #{post.id}"
          post.post_created_at = nil
          post.status = Post::STATUS[:failed_to_fetch_post_create_time]
        end

        Rails.logger.error "Failed to SAVE post #{post.id}: #{post.errors.full_messages}" unless post.save
      end
    end

    self.status = STATUS[:time_updated]
    self.save!

    Rails.logger.info "Finish to update posts create time for Stock: #{self.stock_id}"
  end

  def crawl_posts_details
    self.status = STATUS[:crawling]
    self.save!

    posts_path = self.posts_path
    Rails.logger.info "Start to crawl: #{BASE}/#{posts_path}"
    first_page = Wombat.crawl do
      base_url BASE
      path posts_path

      stock_name css: "div#stockheader span#stockname a"
      stock_code css: "div#stockheader span#stockheadercode a"
      page_calculation xpath: "/html/.//div[@class='pager']/span[@class='pagernums']/@data-pager"

      posts({xpath: "/html/.//div[@class='articleh']"}, :iterator) do
        click_count xpath: "span[1]"
        reply_count xpath: "span[2]"
        # title xpath: "span[3]/a"
        path xpath: "span[3]/a/@href"
      end

      posts_detail({css: "div#articlelistnew div.articleh a[title]"}, :follow) do
        title css: "div#zwconttbt"
        content css: "div#zwconbody div.stockcodec"
        post_created_at css: "div#zwconbot div#zwconbotl" do |time|
          time.blank? ? nil : time.split(/发表时间：/).last
        end
      end
    end

    page_strings = first_page["page_calculation"].split("|")
    posts_count = page_strings[-3].to_i
    posts_per_page = page_strings[-2].to_f
    pages_count = (posts_count / posts_per_page).ceil
    Rails.logger.info "Number of pages: #{pages_count}"

    #if self.stock_id != first_page["stock_code"]
    #  raise "Stock ID is incorrect: #{stock_id} vs #{first_page["stock_code"]}"
    #end
    self.stock_name = first_page["stock_name"]
    
    save_posts_detail(first_page["posts"], first_page["posts_detail"])

    (2..pages_count).each do |i|
      posts_path_i = "#{self.posts_path_no_html}_#{i}.html"
      Rails.logger.info "URL: #{posts_path_i}"
      data = Wombat.crawl do
        base_url BASE
        path posts_path_i

        posts({xpath: "/html/.//div[@class='articleh']"}, :iterator) do
          click_count xpath: "span[1]"
          reply_count xpath: "span[2]"
          path xpath: "span[3]/a/@href"
        end

        posts_detail({css: "div#articlelistnew div.articleh a[title]"}, :follow) do
          title css: "div#zwconttbt"
          content css: "div#zwconbody div.stockcodec"
          post_created_at css: "div#zwconbot div#zwconbotl" do |time|
            time.blank? ? nil : time.split(/发表时间：/).last
          end
        end
      end
      save_posts_detail(data["posts"], data["posts_detail"])
    end

    self.status = STATUS[:crawled]
    self.total_posts = self.posts.size
    self.save!
    return true
  end

  def save_posts(posts, posts_detail=[], update_existing_posts_after=(Time.now-30.days))
    continue_to_crawl = true
    Post.transaction do
      posts.each_index do |i|
        p = posts[i]
        d = posts_detail[i]

        # Remove posts that are not specific to this stock (usually the first 4 posts)
        # next if p["path"].split(",")[1].to_i != self.stock_id[0..6].to_i

        content = nil
        time_parsed = nil
        if d.present?
          content = d["content"].nil? ? nil : d["content"].squish
          time_parsed = d["post_created_at"].blank? ? nil : parse_post_create_time(d["post_created_at"])
        elsif !p["post_created_dt"].blank?
          time_parsed = Time.strptime("#{self.max_possible_post_created_dt.year}-#{p['post_created_dt']}+0800", '%Y-%m-%d%z')
          # Previous Year: sometime Guba sort by time have some posts not in correct order
          if (time_parsed - self.max_possible_post_created_dt) > 5.days
            time_parsed = Time.strptime("#{self.max_possible_post_created_dt.year-1}-#{p['post_created_dt']}+0800", '%Y-%m-%d%z')
          end
        end

        post = Post.find_by(path: p["path"], stock_id: self.stock_id)
        if post.present?
          # Some stocks' forum are really active. Page number changes while crawling. 
          # For example, Post A shows up on Page n, however, it might show up on Page n+1 again since new posts push it down to the next page.
          # We only skip updating posts if they are created 1 day and older. 
          if time_parsed.present? and time_parsed < update_existing_posts_after and (Time.now - post.created_at) > 1.day
            Rails.logger.debug "Do not update posts older than certain days, POST ID: #{post.id}"
            continue_to_crawl = false
            break
          end
        else
          post = Post.new
        end

        post.path = p["path"]
        post.stock_id = self.stock_id
        post.title = p["title"]
        post.click_count = p["click_count"]
        post.post_created_at = time_parsed
        post.content = content

        begin
          post.save!
        rescue Exception => e
          Rails.logger.error "Post not saved properly: #{post.path}, #{e}"
        end
        
        self.max_possible_post_created_dt = time_parsed if time_parsed.present?
      end
    end

    continue_to_crawl
  end

  def update_word_analysis
    self.status = STATUS[:updating]
    self.save!

    words = Word.all
    weight_version = words.first.weight_version

    counter = 0
    # Update word analysis for new Posts (New posts have weight version 0, will be selected automatically) or Posts with older weight version
    while(!(posts = self.posts.without_content.where("word_weight_version != ?", weight_version).limit(PER_PAGE)).blank?) do
      PostWordStat.delete_all(:post_id => posts.map {|p| p.id})
      Post.transaction do
        posts.each do |post|
          negative_weight_for_post = 0
          positive_weight_for_post = 0
          total_weight_for_post = 0
          words.each do |word|
            # word_count = post.title.blank? ? 0 : post.title.scan(word.word).size
            # Count only once for each word, even if it occurs multiple times

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @stocks = Stock.all.paginate(:page => params[:page])
  end

  def new
    @stock = Stock.new
  end

  def create
    failed_to_create = Stock.create_by_stock_ids(stock_params[:stock_ids], stock_params[:delete_old_records])
    if failed_to_create.blank?
      flash[:notice] = "Stocks created successfully."
      redirect_to :action => :index
    else
      flash[:error] = "Failed to create stocks: #{failed_to_create.join(", ")}"
      render "new"
    end
  end

  def crawl_posts_multiple
    if params[:all].present? and params[:all].downcase == 'true'
      Stock.transaction do
        Stock.find_each do |stock|
          set_status_and_start_job(stock, :crawl)
        end
      end
    elsif params[:stock_ids].present? and params[:stock_ids].class == Array
      Stock.transaction do
        Stock.where(:stock_id => params[:stock_ids]).find_each do |stock|
          set_status_and_start_job(stock, :crawl)
        end
      end
    end
    redirect_to :action => :index
  end

  def update_weights_multiple
    if params[:all].present? and params[:all].downcase == 'true'
      Stock.transaction do
        Stock.find_each do |stock|
          set_status_and_start_job(stock, :update_weights)
        end
      end
    elsif params[:stock_ids].present? and params[:stock_ids].class == Array
      Stock.transaction do
        Stock.where(:stock_id => params[:stock_ids]).find_each do |stock|
          set_status_and_start_job(stock, :update_weights)
        end
      end
    end
    redirect_to :action => :index
  end

  def crawl_posts
    @stock = Stock.find(params[:id])
    if @stock.idle?
      @stock.status = Stock::STATUS[:crawling]
      @stock.save
      @stock.crawl_posts
    else
      flash[:error] = "A task is running for #{@stock.stock_id}."
    end
    redirect_to :action => :index
  end

  def update_weights
    @stock = Stock.find(params[:id])
    if @stock.idle?
      @stock.status = Stock::STATUS[:updating]
      @stock.save
      @stock.update_word_analysis
    else
      flash[:error] = "A task is running for #{@stock.stock_id}."
    end
    redirect_to :action => :index
  end

  private

  def stock_params
    params.require(:stock).permit(:stock_ids, :delete_old_records)
  end

  def set_status_and_start_job(stock, job_name)
    if stock.idle?
      status = nil
      action = nil
      case job_name
      when :crawl
        status = Stock::STATUS[:crawling]
        action = :crawl_posts
      when :update_weights
        status = Stock::STATUS[:updating]
        action = :update_word_analysis
      end
    
      stock.status = status
      stock.save
      stock.send(action)
    end
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/index.html.erb
<div>
  <%= link_to "Create New Stock", new_stock_path, :class => "btn btn-primary" %>
  
  <div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      Crawl <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li><%= button_to "All stocks", crawl_posts_multiple_stocks_path(all: true), method: :post %></li>
      <li><a href="#" onclick="MappedOn.Stocks.CrawlPosts();">Selected stocks</a></li>
    </ul>
  </div>

  <div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      Update <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li><%= button_to "All stocks", update_weights_multiple_stocks_path(all: true), method: :post %></li>
      <li><a href="#" onclick="MappedOn.Stocks.UpdateWeights();">Selected stocks</a></li>
    </ul>
  </div>

  <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      Download <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li><a href="<%= download_monthly_summary_posts_path(format: :csv) %>">Summary by month for All</a></li>
      <!--<li><a href="#">Summary by month for Selected</a></li>-->
      <li class="divider"></li>
      <li><a href="#">Summary by week for All</a></li>
      <!--<li><a href="#">Summary by week for Selected</a></li>-->
    </ul>
  </div>
</div>

<% unless @stocks.blank? %>
  <%= form_tag('/stocks', method: :post, id: "stocks") do %>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Stock ID</th>
          <th>Stock Name</th>
          <th>Status</th>
          <th>Total Posts</th>
          <th>Updated Time</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <tr>
            <td><%= check_box_tag 'stock_ids[]', stock.stock_id %></td>
            <td><a href="<%= stock_posts_path(stock.stock_id) %>"><%= stock.stock_id %></a></td>
            <td><%= stock.stock_name %></td>
            <td><%= stock.status %></td>
            <td><%= stock.total_posts %></td>
            <td><%= stock.updated_at %></td>
            <td>
              <%= link_to "Crawl Posts", crawl_posts_stock_path(stock.stock_id), :method => :post, :class => "btn btn-xs btn-primary", :disabled => !stock.idle? %>
              <%= link_to "Update Weights", update_weights_stock_path(stock.stock_id), :method => :post, :class => "btn btn-xs btn-primary", :disabled => !stock.idle? %>
              <%= link_to "Show Chart", chart_stock_posts_path(stock.stock_id), :class => "btn btn-xs btn-success", :disabled => stock.total_posts.nil? %>
              <button class="btn btn-xs btn-danger">Delete</button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

<div class="pagination pull-left"><%= page_entries_info @stocks %></div>
<%= will_paginate @stocks, renderer: BootstrapPagination::Rails, class: "pull-right" %>

app/views/stocks/new.html.erb
<h3>Add a new Stock to Analyze</h3>

<%= form_tag stocks_path, method: :post, class: "form-horizontal", role: "form" do %>
  <div class="form-group">
    <%= label_tag "stock_ids", "Stock IDs", :class => "col-sm-1 control-label" %>
    <div class="col-sm-3"><%= text_area_tag "stock[stock_ids]", nil, :class => "form-control", :rows => 20 %></div>
  </div>
  <div>
    <label>Delete old records: <%= check_box_tag "stock[delete_old_records]" %></label>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
      <button type="submit" class="btn btn-primary">Create</button>
    </div>
  </div>
<% end %>