config/routes.rb
Rails.application.routes.draw do

  root 'stocks#index'

  get '/ping' => 'status#ping'

  resources :stocks do
    member do
      post 'crawl_posts'
      post 'update_weights'
    end

    collection do
      post 'crawl_posts_multiple'
      post 'update_weights_multiple'
    end

    resources :posts do
      collection do
        get 'chart'
      end
    end
  end

  resources :posts do
    collection do
      get 'download_monthly_summary', format: :csv
    end
  end

  resources :words

  resources :baidu_news, only: [:index, :create, :show, :destroy] do
    member do
      get 'download', format: :csv
    end
  end

end

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <% type = type.to_sym %>
  <% if !message.blank? && flash_class(type) %>
    <div class="fade in <%= flash_class(type) %>">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= message.class == Array ? message.join(". ") : message %>
    </div>
    <% flash[type] = nil %>
  <% end  %>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Stock Prediction</span></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
    <li><a href="<%= baidu_news_index_path %>"><%= fa_icon "bar-chart-o", text: "百度" %></a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= fa_icon "file", text: "File" %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Open</a></li>
          <li><a href="#">New</a></li>
          <li><a href="#">Save as</a></li>
          <li><a href="#">Import</a></li>
          <li><a href="#">Export</a></li>
          <li><a href="#">Print</a></li>
          <li><a href="#">Print to DXF File</a></li>
        </ul>
      </li>

      <li><a href="<%= stocks_path %>"><%= fa_icon "bar-chart-o", text: "股票" %></a></li>
      <li><a href="#"><%= fa_icon "list", text: "帖子" %></a></li>
      <li><a href="<%= words_path %>"><%= fa_icon "book", text: "词库" %></a></li>
      <li><a href="#"><%= fa_icon "upload", text: "Output" %></a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search...">
        </div>
      </form>
      <li><a href="#">Help</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>User Account</b> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</header>