config/routes.rb
Rails.application.routes.draw do

  root 'stocks#index'

  get '/ping' => 'status#ping'

  resources :stocks do
    member do
      post 'crawl_posts'
      post 'update_weights'
    end

    collection do
      post 'crawl_posts_multiple'
      post 'update_weights_multiple'
    end

    resources :posts do
      collection do
        get 'chart'
      end
    end
  end

  resources :posts do
    collection do
      get 'download_monthly_summary', format: :csv
    end
  end

  resources :words

  resources :baidu_news, only: [:index, :create, :show, :destroy] do
    member do
      get 'download', format: :csv
    end
  end

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.all
  end

  def new
    @word = Word.new
  end

  def create
    @word = Stock.new(word_params)
    if @word.save
      flash[:notice] = "Word created successfully."
      redirect_to :action => :index
    else
      render "new"
    end
  end

  private

  def word_params
    params.require(:word).permit(:word, :weight)
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/index.html.erb
<%= link_to "Create New Word", new_word_path, :class => "btn btn-primary" %>
<% unless @words.blank? %>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Word</th>
        <th>Weight</th>
        <th>Updated Time</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @words.each do |word| %>
        <tr>
          <td><%= word.word %></td>
          <td><%= word.weight %></td>
          <td><%= word.updated_at %></td>
          <td>
            <button class="btn btn-xs btn-primary">Edit</button>
            <button class="btn btn-xs btn-danger">Delete</button>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/words/new.html.erb
<h3>Add a new Word</h3>

<%= form_for @word, :html => {:class => "form-horizontal", :role => "form"} do |f| %>
  <div class="form-group">
    <%= f.label :word, "Word", :class => "col-sm-1 control-label" %>
    <div class="col-sm-3"><%= f.text_field :word, :class => "form-control" %></div>
  </div>
  <div class="form-group">
    <%= f.label :weight, "Weight", :class => "col-sm-1 control-label" %>
    <div class="col-sm-3"><%= f.text_field :weight, :class => "form-control" %></div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-10">
      <button type="submit" class="btn btn-primary">Create</button>
    </div>
  </div>
<% end %>