config/routes.rb
Rails.application.routes.draw do

  root 'stocks#index'

  get '/ping' => 'status#ping'

  resources :stocks do
    member do
      post 'crawl_posts'
      post 'update_weights'
    end

    collection do
      post 'crawl_posts_multiple'
      post 'update_weights_multiple'
    end

    resources :posts do
      collection do
        get 'chart'
      end
    end
  end

  resources :posts do
    collection do
      get 'download_monthly_summary', format: :csv
    end
  end

  resources :words

  resources :baidu_news, only: [:index, :create, :show, :destroy] do
    member do
      get 'download', format: :csv
    end
  end

end

app/controllers/baidu_news_controller.rb
class BaiduNewsController < ApplicationController
  def index
    paginated_baidu_tasks
    @baidu_task = BaiduTask.new
  end

  def create
    @baidu_task = BaiduTask.new(baidu_task_params)
    if @baidu_task.save
      @baidu_task.start
      flash[:notice] = "A new search is created"
      render action: :show
    else
      paginated_baidu_tasks
      flash[:error] = @baidu_task.errors.full_messages
      render :index
    end
  end

  def show
    unless baidu_task.nil?
      flash[:error] = "Record not found"
      redirect_to action: :index
    end
  end

  def download
    baidu_task
    respond_to do |format|
      format.csv { render_csv }
    end
  end

  def destroy
    if baidu_task
      if baidu_task.destroy
        flash[:notice] = "Baidu news search is deleted successfully"
      else
        flash[:error] = "Failed to delete"
      end
    else
      flash[:error] = "Record not found"
    end
  end

  private
  def baidu_task
    @baidu_task = BaiduTask.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def paginated_baidu_tasks
    @baidu_tasks = BaiduTask.all.order("updated_at DESC").paginate(:page => params[:page])
  end

  def baidu_task_params
    params.require(:baidu_task).permit(:start_date, :end_date)
  end

  def set_file_headers
    file_name = "BaiduNews_#{@baidu_task.start_date}-#{@baidu_task.end_date}.csv"
    headers["Content-Type"] = "text/csv"
    headers["Content-Disposition"] = "attachment; filename=\"#{file_name}\""
  end

  def set_streaming_headers
    #nginx doc: Setting this to "no" will allow unbuffered responses suitable for Comet and HTTP streaming applications
    headers['X-Accel-Buffering'] = 'no'
    headers["Cache-Control"] ||= "no-cache"
    headers.delete("Content-Length")
  end

  def render_csv
    set_file_headers
    set_streaming_headers
    response.status = 200

    #setting the body to an enumerator, rails will iterate this enumerator
    self.response_body = csv_lines
  end

  def csv_lines
    Enumerator.new do |y|
      y << BaiduNewsStat.csv_header.to_s

      #ideally you'd validate the params, skipping here for brevity
      @baidu_task.baidu_news_stats.each do |bns|
        y << bns.to_csv.to_s
      end
    end
  end
end

app/helpers/baidu_news_helper.rb
module BaiduNewsHelper
end

app/views/baidu_news/_baidu_tasks.html.erb
<% unless baidu_tasks.blank? %>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Task ID</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Total</th>
        <th>Processed</th>
        <th>Status</th>
        <th>Created Time</th>
        <th>Updated Time</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% baidu_tasks.each do |baidu_task| %>
        <tr id="baidu-task-<%= baidu_task.id %>">
          <td><%= baidu_task.id %></td>
          <td><%= baidu_task.start_date %></td>
          <td><%= baidu_task.end_date %></td>
          <td><%= baidu_task.total %></td>
          <td><%= baidu_task.processed %></td>
          <td><%= baidu_task.status %></td>
          <td><%= baidu_task.created_at %></td>
          <td><%= baidu_task.updated_at %></td>
          <td>
            <%= link_to "Download", download_baidu_news_path(baidu_task.id, format: "csv"), :method => :get, :class => "btn btn-xs btn-primary", :disabled => !baidu_task.downloadable? %>
            <%= link_to "Delete", baidu_news_path(baidu_task.id), :method => :delete, :class => "btn btn-xs btn-danger", :remote => true, :data => {:confirm => "Are you sure to delete?"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  There is no search.
<% end %>

app/views/baidu_news/destroy.js.erb
<% if flash[:error] %>
  alert("<%= flash[:error] %>");
<% else %>
  $("tr#baidu-task-<%= @baidu_task.id %>").remove();
  alert("<%= flash[:notice] %>");
<% end %>

app/views/baidu_news/index.html.erb
<%= form_for @baidu_task, url: baidu_news_index_path, method: :post, html: {class: 'form-inline', role: 'form'} do |f| %>
  <div class="form-group">
    <label for="baidu_task_start_date">Start Date: </label>
    <%= f.text_field :start_date, :class => "datepicker form-control", :placeholder => 'yyyy-mm-dd' %>
  </div>

  <div class="form-group">
    <label for="baidu_task_end_date">End Date: </label>
    <%= f.text_field :end_date, :class => "datepicker form-control", :placeholder => 'yyyy-mm-dd' %>
  </div>

  <button type="submit" class="btn btn-primary">Create new search</button>
<% end %>

<h3>Previous Search</h3>
<%= render partial: "baidu_tasks", locals: {baidu_tasks: @baidu_tasks} %>

<div class="pagination pull-left"><%= page_entries_info @baidu_tasks %></div>
<%= will_paginate @baidu_tasks, renderer: BootstrapPagination::Rails, class: "pull-right" %>

<script type="text/javascript">
  $(".datepicker").datepicker({format: 'yyyy-mm-dd'});
</script>

app/views/baidu_news/show.html.erb
<%= render partial: "baidu_tasks", locals: {baidu_tasks: [@baidu_task]} %>